baseurl = "https://ssunrh.github.io/"
title = "sarah sun"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "i draw but only sometimes"
  copyright = "&copy;2023 Sarah Sun"
  sidebarAbout = [
    "welcome to my portfolio website!"
  ]

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  identifier = "art"
  name = "home"
  url = "art/"
  home = true
  
  [[params.navlinks]]
  identifier = "digital"
  name = "digital illustration"
  url = "digital/"
  
  [[params.navlinks]]
  identifier = "traditional"
  name = "fine arts"
  url = "traditional/"
  
  [[params.navlinks]]
  identifier = "merch"
  name = "merch design"
  url = "merch/"
  parent = "digital"
  
  [[params.navlinks]]
  identifier = "graphic"
  name = "graphic design"
  url = "graphic/"
  
  [[params.navlinks]]
  name = "about"
  url = "about/"

  [params.social]
  email         = "sarahandsun@gmail.com"
  linkedin      = "https://www.linkedin.com/in/ssunrh/"
